
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: TERRAKUBE_OIDC_CLIENT_ID
    remoteRef:
      key: "10e9c970-5f4d-4bd4-b883-b3b5007ea7e3"
  - secretKey: TERRAKUBE_OIDC_CLIENT_SECRET
    remoteRef:
      key: "0e907bab-bca2-465b-8e64-b3b5007eb7a7"
