---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/objectbucket.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: terrakube-bucket
  namespace: gdd-security
spec:
  bucketName: terrakube
  storageClassName: ceph-bucket