---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  caching: true
  path: /data/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/213795
  link: https://github.com/onedr0p
  buttons:
    - name: Github
      link: https://github.com/negativefeedback
    - name: Homelab
      link: https://github.com/negativefeedback/home-ops

web:
  port: ${GATUS_WEB_PORT}

alerting:
  ntfy:
    url: "https://alerts.gddnet.io"
    topic: ${GATUS_NTFY_TOPIC}
    token: ${GATUS_NTFY_TOKEN}
    priority: 5 # Optional, adjust as needed
    default-alert:
      description: "ðŸš¨ Gatus Alert: {{ .Name }} has failed its health check"
      failure-threshold: 3
      send-on-resolved: true
  discord:
    webhook-url: ${GATUS_DISCORD_WEBHOOK}
    default-alert:
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 5
  github:
    repository-url: "https://github.com/NegativeFeedback/homeops"
    token: ${GATUS_GITHUB_TOKEN}
    default-alert:
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 5