base-url: "https://alerts.gddnet.io"
cache-file: "/data/cache.db"
attachment-cache-dir: "/data/attachments"
upstream-base-url: "https://ntfy.sh"
listen-http: ":8080"
smtp-server-listen: ":25"
smtp-server-domain: "alerts.gddnet.io"
smtp-server-addr-prefix: ""
behind-proxy: true
enable-metrics: true
metrics-listen-http: "[::]:9090"
####
auth-file: /data/user.db
auth-default-access: "deny-all"
enable-login: true