
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: "1daaedf4-8e7a-4122-a04f-b39f016b72c7"
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: "6049fe7b-9563-44f1-9fe2-b39f016b9f7a"
  - secretKey: SPARKY_FITNESS_DB_NAME
    remoteRef:
      key: "514f2c07-df56-4827-a7c6-b39f016bc1c3"
  - secretKey: SPARKY_FITNESS_DB_HOST
    remoteRef:
      key: "e478189e-a155-4dbe-adbd-b392016de319"
  - secretKey: SPARKY_FITNESS_DB_PASSWORD
    remoteRef:
      key: "722dfa88-784d-42ee-9738-b39f016bf283"
  - secretKey: SPARKY_FITNESS_DB_USER
    remoteRef:
      key: "24b20985-14e7-4349-a19f-b39f016c313b"
  - secretKey: SPARKY_FITNESS_APP_DB_PASSWORD
    remoteRef:
      key: "722dfa88-784d-42ee-9738-b39f016bf283"
  - secretKey: SPARKY_FITNESS_APP_DB_USER
    remoteRef:
      key: "24b20985-14e7-4349-a19f-b39f016c313b"
  - secretKey: SPARKY_FITNESS_API_ENCRYPTION_KEY
    remoteRef:
      key: "48d79bf4-d16d-4928-939d-b39f016caf47"
  - secretKey: JWT_SECRET
    remoteRef:
      key: "98fea8d1-ad14-48aa-a99a-b39f016d0d27"
  - secretKey: SPARKY_FITNESS_ADMIN_EMAIL
    remoteRef:
      key: "b818f3b0-5d17-4893-baeb-b39f016d7943"

