
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secret
  namespace: observability
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: GATUS_NTFY_TOKEN
    remoteRef:
      key: "fad339e9-4070-4a50-9056-b39b013d05c0"
  - secretKey: GATUS_NTFY_TOPIC
    remoteRef:
      key: "dc02cf2b-90ff-4f03-8a99-b39b013ce08e"
  - secretKey: GATUS_DISCORD_WEBHOOK
    remoteRef:
      key: "9b6c51d0-76a6-4482-a61f-b39b013d7925"
  - secretKey: GATUS_GITHUB_TOKEN
    remoteRef:
      key: "855c4350-d7db-4f04-8622-b39b013e94bd"