
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-secret
  namespace: gdd-plex
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: "2ea4dcfd-7a29-4db7-807b-b3950073442c"
  - secretKey: JWT_SECRET
    remoteRef:
      key: "ea932799-89d5-466f-a0a3-b39500732304"


