---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gdd-service
components:
  - ../../components/common
resources:
  - ./calibre/ks.yaml
  - ./ntfy/ks.yaml
  - ./donetick/ks.yaml
  - ./tandoor/ks.yaml
  - ./homepage/ks.yaml
  - ./minecraft/ks.yaml
  - ./foundryvtt/ks.yaml
  - ./minecraft-create/ks.yaml
  - ./nextcloud/ks.yaml
  - ./monica/ks.yaml
  - ./paperless/ks.yaml
  - ./sparkyfitness/ks.yaml