
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: PAPERLESS_ADMIN_USER
    remoteRef:
      key: "4ce0110b-7480-47cb-ab44-b393007f2c03"
  - secretKey: PAPERLESS_ADMIN_PASSWORD
    remoteRef:
      key: "020cc3c8-798e-44c5-ae80-b393007f4f0e"
  - secretKey: PAPERLESS_SECRET_KEY
    remoteRef:
      key: "719b6bea-a27c-4d26-8f5a-b393007f6145"

