
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tidarr-secret
  namespace: gdd-plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: "REPLACE-WITH-BITWARDEN-UUID"
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: "REPLACE-WITH-BITWARDEN-UUID"
