
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: gdd-plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: HOMEPAGE_VAR_SONARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_TANDOOR_TOKEN
    remoteRef:
      key: "9a48b0fb-72d4-497d-969b-b39c015bdce3"
