---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-db-secret
  namespace: gdd-social
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-database
    kind: ClusterSecretStore
  target:
    name: synapse-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        POSTGRES_URL: "postgresql://{{ .username }}:{{ .password }}@postgres-rw.database.svc.cluster.local:5432/synapse"
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "synapse"
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: synapse-db-secret
        property: username
    - secretKey: password
      remoteRef:
        key: synapse-db-secret
        property: password
