---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-dbapp-secret
  namespace: gdd-social
spec:
  refreshInterval: 12h
  target:
    name: synapse-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: synapse
        password: "{{ .password }}"
        POSTGRES_URL: "postgresql://synapse:{{ .password }}@postgres-rw.database.svc.cluster.local:5432/synapse"
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "synapse"
        POSTGRES_USER: "synapse"
        POSTGRES_PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: synapse-db-password
          namespace: database
