---
originRequest:
  originServerName: "external.securitylab.io"

ingress:
  - hostname: "securitylab.io"
    service: &svc http://cilium-gateway-seclabexternal.kube-system.svc.cluster.local
    originRequest:
      noTLSVerify: true
  - hostname: "*.securitylab.io"
    service: *svc
    originRequest:
      noTLSVerify: true
  - service: http_status:404
    originRequest:
      noTLSVerify: true
