---
originRequest:
  originServerName: "external.gddnet.io"
  noTLSVerify: true

ingress:
  - hostname: "securitylab.io"
    service: &svc https://cilium-gateway-seclabexternal.kube-system.svc.cluster.local
  - hostname: "*.securitylab.io"
    service: *svc
  - hostname: "newsso.securitylab.io"
    service: *svc
  - service: http_status:404

