---
originRequest:
  originServerName: "external.securitylab.io"

ingress:
  - hostname: "securitylab.io"
    service: &svc https://cilium-gateway-seclabexternal.kube-system.svc.cluster.local
  - hostname: "*.securitylab.io"
    service: *svc
  - service: http_status:404
