
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: "8239790e-50e0-4498-b3df-b21b007fe74a"
  - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
    remoteRef:
      key: "b9dd5489-bba6-4f69-8c79-b21b0063d58e"
  - secretKey: AUTHENTIK_POSTGRESQL__USER
    remoteRef:
      key: "d0ec47e1-16fb-4ab5-8273-b228013211b0"
  - secretKey: AUTHENTIK_POSTGRESQL__NAME
    remoteRef:
      key: "9920a731-e663-4c35-b18b-b22801322a0e"
  - secretKey: AUTHENTIK_POSTGRESQL__HOST
    remoteRef:
      key: "e39f4c0d-040a-4c96-8fcf-b228013244df"
  - secretKey: AUTHENTIK_EMAIL__HOST
    remoteRef:
      key: "e65fe612-ee30-4f93-897d-b3930179484d"
  - secretKey: AUTHENTIK_EMAIL__PORT
    remoteRef:
      key: "b17144a9-5742-4d49-a64c-b39301796f53"
  - secretKey: AUTHENTIK_EMAIL__USERNAME
    remoteRef:
      key: "4f5f7dda-b08b-4000-9163-b39301799dbf"
  - secretKey: AUTHENTIK_EMAIL__PASSWORD
    remoteRef:
      key: "f9eb8ea1-0972-4628-b79d-b3930179b904"
  - secretKey: AUTHENTIK_EMAIL__FROM
    remoteRef:
      key: "a84b1f1e-0307-40e3-9988-b3930179fb52"
  - secretKey: HOMEPAGE_VAR_AUTHENTIK_TOKEN
    remoteRef:
      key: "4ca45515-79bc-44fb-8e78-b39c00584b45"


#ak test_email <to_address>