---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gdd-security
components:
  - ../../components/common
resources:
  - ./authentik/ks.yaml
  - ./openbao/ks.yaml
  - ./terrakube/ks.yaml