# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: securitylab-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:yRirSGTuoBwwv1DuUDLrxBMtJzI6JozH7aRNEl4bqhZbCZmg3clQE3T+LgD+FmlX3TC+e+ccPVE2dZw7grdjymXswAydfTpkbk2boQGfcoqU8Lp5eTm4v55u5uYdrRf0cY+bdgeH0CqM/+QJl1DtWVgH+SXXOoEwE7MHZtW1I9Gc+aRkpy9JyK0tF7IWyiEFiX5SK53niBTr9ABM1305om3AEWOLzDehhXW2yZkklFrYAlS6,iv:FARawnIAvIxa2Eeuz93kGLNyPvc8KVbiG3e8b/FhDBU=,tag:e9UpOrLxAo1Zy6GhzovZdA==,type:str]
sops:
    age:
        - recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MzBFVXRZSWtUcGFjY2R5
            ck1PS2JXUURSWkJFN0NsMTNZb1JLQk1pNTJNClJhRm1wMStKSWNNM1AxSTdBZlpD
            SXNLcE9SVktHMGhYY1BRZ2FUUDJybm8KLS0tIGNJSHNhQzVpSHViSm5BMGRlVm9Z
            UW9IMnBlMG5xQVZrVGk5L2Z2akNORDAKtskyW/84yFveFpNyMytIUvkx6e9DRVcr
            jBWeEpnmDUFbua5iglBetIKV8qvGiwdq6iz92V+kxcybd8/jV+weZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:06:00Z"
    mac: ENC[AES256_GCM,data:kSbdWHmsuq7c8jlJ99vDUWApsQH3d77JpT7nCfb1d8UAbE40t207vxVXVj6Ccjr8JIuHwcBS+y3wsilhe8lW5a51O+DcnNpIqOjtFrXRSPhed9n1uD9WOr2OoO0/0BFVhrPrQ0+E0I7nlFF+kgQwN3tw7vnU2JjVgKxYh6QeFRg=,iv:zWQbw6zTUiy5RfCpQGipMmNN0P9H68ECU62nnCrzO+c=,tag:fNv6+koLlcew8s+Jh+YDfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
