
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: "8239790e-50e0-4498-b3df-b21b007fe74a"

#        OIDC_ISSUER_URL: "https://sso.gddnet.io/application/o/headlamp/"
#        OIDC_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
#        OIDC_CLIENT_SECRET: "{{ .HEADLAMP_CLIENT_SECRET }}"
#        OIDC_SCOPES: "openid email profile"