---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: nextcloud-data-dst
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: nextcloud-data-local-volsync
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 1Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    capacity: 500Gi
    moverSecurityContext:
      fsGroup: 82
      runAsGroup: 82
      runAsUser: 82